### PR TITLE
Add pointer and span versions

### PR DESCRIPTION
**Pull request by delreluca**
# Purpose of this PR

The purpose of this PR is to address #8 by including pointer versions and automatically creating span and array wrappers which call the pointer versions.

## How it works

This PR introduces a Roslyn source generator that looks at bare unsafe (i.e. taking `T*` arguments) P/Invoke definitions and automatically generates wrappers that take `T[]` and `Span<T>`.

Some resources for those not familiar with source generators:

- [Source Generator Cookbook](https://github.com/dotnet/roslyn/blob/main/docs/features/source-generators.cookbook.md)
- [Video from JetBrains .NET days](https://www.youtube.com/watch?v=azJm_Y2nbAI)
- [Blog series by Andrew Lock](https://andrewlock.net/series/creating-a-source-generator/)

### Why not incremental

Why did I go for a regular instead of an incremental source generator? Honestly that’s what I am familiar with (even though I posted resources about incremental ones as well). I guess for one-off generation they are good enough. If we expected people to use this generator in their own projects an incremental one would make a lot of sense though.

### What do we generate

We generate

- simple wrappers that swap `T*` with `Span<T>` and `T[]` (the latter should be superfluous due to automatic conversions but we don’t want to break API compatibility)
- in addition versions that infer the length (except for `Lapack` where I was unsure about the result): works by finding a single `int` argument with a single character name (typically `n` or `N`) and removing it from the wrapper, inferring it from the first transformed argument’s length
- in addition, only for `Blas` and `Vml`: add versions with `iniX` whenever we have an argument `incX` and _X_ is a name of length 1 or 2 and is not `A` (which never had an `iniA`). This is also not needed anymore with `Span<T>` since you can just slice them, but we keep it for compatibility

### Where do the pointer signatures come from

I used Regex search and replace to transform the existing ones. They are put into an `Unsafe` static nested class (which the generator picks up) and have their names aligned with the existing wrapped ones by using `EntryPoint`.

### Testing

I added a test for the source generator itself and made sure the existing tests pass. Since the existing tests use the array versions which now call the pointer versions we have decent test coverage.

### How does auto-generated code look like

Check e.g. `MKL.NET/obj/$config/$tfm/$rid/generated/MKL.NET.WrapperGenerator/MKLNET.WrapperGenerator.WrapperGenerator/Blas.Wrappers.g.cs` after building MKL.NET. Here is an excerpt

<details>
<summary>axpby wrappers</summary>

```csharp
///<summary>Calls the MKL function <c>axpby</c> by pinning the given data during the computation.</summary>
[global::System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
public static void axpby(int N, float alpha, float[] X, int incX, float beta, float[] Y, int incY)
{
    unsafe
    {
        fixed(float* XPinned = X)
        fixed(float* YPinned = Y)
        {
            Unsafe.axpby( N,  alpha,  XPinned,  incX,  beta,  YPinned,  incY);
        }
    }
}
///<remarks>This version infers the length parameter <c>N</c> from <paramref name="X" />'s length.</remarks>
///<summary>Calls the MKL function <c>axpby</c> by pinning the given data during the computation.</summary>
[global::System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
public static void axpby(float alpha, float[] X, int incX, float beta, float[] Y, int incY)
{
    unsafe
    {
        fixed(float* XPinned = X)
        fixed(float* YPinned = Y)
        {
            Unsafe.axpby( X.Length,  alpha,  XPinned,  incX,  beta,  YPinned,  incY);
        }
    }
}
///<remarks>This version takes offsets in the form of <c>iniX</c> arguments. Consider using the Span version with slicing instead.</remarks>
///<summary>Calls the MKL function <c>axpby</c> by pinning the given data during the computation.</summary>
[global::System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
public static void axpby(int N, float alpha, float[] X, int iniX, int incX, float beta, float[] Y, int iniY, int incY)
{
    unsafe
    {
        fixed(float* XPinned = &X[iniX])
        fixed(float* YPinned = &Y[iniY])
        {
            Unsafe.axpby( N,  alpha,  XPinned,  incX,  beta,  YPinned,  incY);
        }
    }
}

///<summary>Calls the MKL function <c>axpby</c> by pinning the given data during the computation.</summary>
[global::System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
public static void axpby(int N, float alpha, global::System.Span<float> X, int incX, float beta, global::System.Span<float> Y, int incY)
{
    unsafe
    {
        fixed(float* XPinned = X)
        fixed(float* YPinned = Y)
        {
            Unsafe.axpby( N,  alpha,  XPinned,  incX,  beta,  YPinned,  incY);
        }
    }
}
///<remarks>This version infers the length parameter <c>N</c> from <paramref name="X" />'s length.</remarks>
///<summary>Calls the MKL function <c>axpby</c> by pinning the given data during the computation.</summary>
[global::System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
public static void axpby(float alpha, global::System.Span<float> X, int incX, float beta, global::System.Span<float> Y, int incY)
{
    unsafe
    {
        fixed(float* XPinned = X)
        fixed(float* YPinned = Y)
        {
            Unsafe.axpby( X.Length,  alpha,  XPinned,  incX,  beta,  YPinned,  incY);
        }
    }
}
```

</details>

## Coverage of MKL functions

I covered `Blas`, `Feast`, `Lapack` and `Vml`. I did not cover

- Functions not included in MKL itself
- Solver: seems to have non trivial wrappers
- VSL: same, and here it makes sense since the VSL API needs pinned pointers, so not sure how a good wrapper would look like
- [BLAS-like functions `?imatadd` `?imatcopy`](https://www.intel.com/content/www/us/en/develop/documentation/onemkl-developer-reference-fortran/top/blas-and-sparse-blas-routines/blas-like-extensions/mkl-imatcopy.html): There seems to be problem with using the original definition with pointers. The original definition uses `int` for `size_t`, and at least on my machine using `int` and `double*` will lead to segfaults. I have since found out that (according to [ClangSharpPInvokeGenerator](https://github.com/dotnet/ClangSharp#generating-bindings)) `size_t` should have been `nuint` (and that one works). Apparently the stub generated by the Jitter when encountering arrays to marshal is a bit more tolerant with mismatching types? I’m not sure to be honest. See possible improvements for how I would handle it in another PR.

## Possible improvements

- Check in generated code: See [Andrew Lock’s blog post](https://andrewlock.net/creating-a-source-generator-part-6-saving-source-generator-output-in-source-control/) if needed. For now I added `<EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>` to the main project file. It will output the generated code but by default to the `obj` folder, so it won’t be checked in. The blog post describes how to change the path to check it in, if desired
- We could add `[SkipLocalsInit]` on the wrappers. This would require C# 9.0 and a polyfill NuGet to add the attribute (which is only available in .NET 5+). I would suggest doing it in another PR to assess performance impact separately.
- Adding tests for the `Span<T>` versions
- Add some way to mark input-only arguments and render them `ReadOnlySpan<T>` instead of `Span<T>` for better usability (maybe we could use `[In]` for that). I shied away from this since it’s a lot of work to figure out which arguments are read-only. I would suggest doing this in separate PR
- Include the BLAS-like functions with correct `nuint` (or `UIntPtr`) definitions in a separate `BlasLike` class so they can be auto-wrapped as well. We can have the existing `int` signatures delegate to the new wrappers then. I would suggest doing this in a separate PR

### CODE REVIEW

**Comment by PhilPJL** [comment]
Did you consider using LibraryImportAttribute?

**Comment by delreluca** [comment]
> Did you consider using LibraryImportAttribute?

Hi @PhilPJL, I might be wrong but isn’t it .NET 7 only?

**Comment by PhilPJL** [comment]
Ok fair enough, it is unfortunately.

**Comment by delreluca** [comment]
I have had look at it some weeks ago when .NET 7 came out and for arrays it basically just pinned them and then called a pointer version. It also added `[SkipLocalsInit]`. So it’d be very similar but I don’t think it would allow us to do transformations like inferring length parameters.

**Comment by PhilPJL** [comment]
By 'just pinning' do you mean this:

```
    static unsafe partial class MKLNativeMethods
    {
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Interop.LibraryImportGenerator", "7.0.7.1805")]
        [System.Runtime.CompilerServices.SkipLocalsInitAttribute]
        private static partial void vdMul(int n, global::System.ReadOnlySpan<double> a, global::System.ReadOnlySpan<double> b, global::System.Span<double> r)
        {
            // Pin - Pin data in preparation for calling the P/Invoke.
            fixed (void* __a_native = &global::System.Runtime.InteropServices.Marshalling.ReadOnlySpanMarshaller<double, double>.ManagedToUnmanagedIn.GetPinnableReference(a))
            fixed (void* __b_native = &global::System.Runtime.InteropServices.Marshalling.ReadOnlySpanMarshaller<double, double>.ManagedToUnmanagedIn.GetPinnableReference(b))
            fixed (void* __r_native = &global::System.Runtime.InteropServices.Marshalling.SpanMarshaller<double, double>.ManagedToUnmanagedIn.GetPinnableReference(r))
            {
                __PInvoke(n, (double*)__a_native, (double*)__b_native, (double*)__r_native);
            }

            // Local P/Invoke
            [System.Runtime.InteropServices.DllImportAttribute("mkl_rt.dll", EntryPoint = "vdMul", ExactSpelling = true)]
            [System.Runtime.InteropServices.UnmanagedCallConvAttribute(CallConvs = new System.Type[]{typeof(global::System.Runtime.CompilerServices.CallConvCdecl)})]
            static extern unsafe void __PInvoke(int n, double* a, double* b, double* r);
        }
    }
```

Which seems to be a bit more involved than `fixed(float* XPinned = X)` but if that works, great.

Did you handle methods with Complex values?  This is working ok for me

```
    [LibraryImport("mkl_rt.dll")]
    [UnmanagedCallConv(CallConvs = new [] { typeof(CallConvCdecl) })]
    private static partial void vzMul(int n, ReadOnlySpan<MKLComplex16> a, ReadOnlySpan<MKLComplex16> b, Span<MKLComplex16> r);

    public static void Multiply(ReadOnlySpan<Complex> a, ReadOnlySpan<Complex> b, Span<Complex> r)
    {
        Guard.IsGreaterThanOrEqualTo(b.Length, a.Length);
        Guard.IsGreaterThanOrEqualTo(r.Length, a.Length);

        var lhs = MemoryMarshal.Cast<Complex, MKLComplex16>(a);
        var rhs = MemoryMarshal.Cast<Complex, MKLComplex16>(b);
        var res = MemoryMarshal.Cast<Complex, MKLComplex16>(r);

        vzMul(lhs.Length, lhs, rhs, res);
    }

public struct MKLComplex16
{
    public double Real;
    public double Imag;
}
```

Although after benchmarking vzMul seems to be 50% of the speed of a simple .NET for loop.  I hope I'm wrong there.

**Comment by delreluca** [comment]
Yes, this looks like the code I remember from experimenting. You are right in that it introduces a whole new machinery of marshallers, but if you follow the code (e.g. via source.dot.net or decompiling) it ends up just fixing the span/array. However this allows you to customise marshalling if you need to (all these marshalling classes are .NET 7 only as well, mind you)

I haven’t tried complex numbers in MKL because I did not encounter them in this project. But in IPP (other Intel library) the same (struct with Re and Im) works. You can’t use the struct with `stackalloc` unfortunately but you can use `Unsafe` and `MemoryMarshal`:

```csharp
Span<double> xs = stackalloc double[]{1,2,3,4};
var zs = MemoryMarshal.CreateSpan(ref Unsafe.As<double,MKLComplex16>(ref xs[0]), 2);
// zs is now a Span<MKLComplex16> with 1+2i, 3+4i
```

Regarding benchmarking, just an anecdote (I didn’t check `vzMul`): at work I tried benchmarking IPP and `Span.Clear` and `Span.Fill` are as performant as the corresponding IPP functions. `Span` doesn’t come with arithmetic operations, but using vector intrinsics (see e.g. [LitMath](https://github.com/matthewkolbe/LitMath)) addition also becomes basically as fast as the IPP addition. It’s an interesting development, maybe we won’t need MKL/IPP for the simple stuff soon enough? 😄

**Comment by AnthonyLloyd** [comment]
Many thanks for this its really good. I'm going to merge this and do a bit of housekeeping on the code as it hasn't been done for a while.

**Comment by PhilPJL** [comment]
Can I suggest, if you're not already doing this, make input params ReadOnlySpan<T>.

**Comment by delreluca** [comment]
> Can I suggest, if you're not already doing this, make input params ReadOnlySpan.

This is already in the “possible improvements” list above. The reason why I haven’t done it yet is that determining whether a parameter is read-only seems to be a manual process

If you have a list of input parameters per routine or some way of inferring them, that would help me a lot

**Comment by PhilPJL** [comment]
I'm no expert on MKL but it looks like there's a consistent naming pattern where 'a', 'b', 'n' are inputs and 'r' is the output.

Also looking at mkl_vml_functions.h we have for example Cos

```
/* Cosine: r[i] = cos(a[i]) */
_MKL_API(void,VSCOS,(const MKL_INT *n, const float a[], float r[]))
_MKL_API(void,VDCOS,(const MKL_INT *n, const double a[], double r[]))
_mkl_api(void,vscos,(const MKL_INT *n, const float a[], float r[]))
_mkl_api(void,vdcos,(const MKL_INT *n, const double a[], double r[]))
_Mkl_Api(void,vsCos,(const MKL_INT n, const float a[], float r[]))
_Mkl_Api(void,vdCos,(const MKL_INT n, const double a[], double r[]))

_MKL_API(void,VMSCOS,(const MKL_INT *n, const float a[], float r[], MKL_INT64 *mode))
_MKL_API(void,VMDCOS,(const MKL_INT *n, const double a[], double r[], MKL_INT64 *mode))
_mkl_api(void,vmscos,(const MKL_INT *n, const float a[], float r[], MKL_INT64 *mode))
_mkl_api(void,vmdcos,(const MKL_INT *n, const double a[], double r[], MKL_INT64 *mode))
_Mkl_Api(void,vmsCos,(const MKL_INT n, const float a[], float r[], MKL_INT64 mode))
_Mkl_Api(void,vmdCos,(const MKL_INT n, const double a[], double r[], MKL_INT64 mode))
```

where inputs are const.

Note the optional mode parameter.  By default the mode is 'high accuracy' which is one explanation of the slow performance of complex multiply.  Changing that to 'performance' mode makes complex multiply run in the same time as a simple C# loop (unfortunately not better).

The mode can be globally changed if required.

**Comment by delreluca** [comment]
> I'm no expert on MKL but it looks like there's a consistent naming pattern where 'a', 'b', 'n' are inputs and 'r' is the output.

That seems to be the case for VML, but BLAS for example is not consistent. But `const` seems to be used correctly in the other header files as well, so I can try to use that information. Haven’t thought of looking there 👍 

Re the performance: have you tried adding `[System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]` on the wrapper? Are you trying long vectors like 10,000 or 100,000 or rather small ones?

**Comment by PhilPJL** [comment]
As I expected using AggressiveInlining made no difference.  The overhead of the function call is negligible.
I was using vectors of length 400 and have now tried 40000.   

For 40000 multiply double stayed the same, MKL is 2x faster.  Multiply complex does improve, so high accuracy mode takes the same as a loop and performance mode is twice as fast.  Trigonometric functions which were already 5x faster than a loop are now 20x faster.  Run on an 8700k.

For length 40 now MKL multiply double and complex are slower than a loop.  Trig functions are still faster but not as much.  

So unfortunately it's not a simple choice to switch to using MKL vector functions.

Here's my benchmark code [https://github.com/PhilPJL/MklBenchmark](https://github.com/PhilPJL/MklBenchmark ).

I'm interested to find out how to run the MKL code on the Intel GPU, and a comparison using a 13th gen CPU would be also be interesting.

**Comment by delreluca** [comment]
@PhilPJL: It could also be that your C# loop is vectorised by the JIT (RyuJIT with tiered compilation seems to be able to do that from what I’ve read). And I didn’t know that MKL supported Intel GPUs that’s cool. Of course there you'd have overhead with memory transfer/pinning.

@AnthonyLloyd: The suggestion by @PhilPJL looks promising, `const` is used on the header files for BLAS, LAPACK and VML. Doing some regex work to annotate all params `const (double|float)*` and make the generator emit `ReadOnlySpan` for them seems conservative to me. If you’re not in a hurry with the next release maybe I can adapt the signatures end of next week/week after that, as it would be a breaking change.

**Comment by AnthonyLloyd** [comment]
@delreluca sure sounds good.

**Pull request merged**
