### PR TITLE
Add single precision matrix and vector

### LINKED ISSUE #19: Would it be possible to add single precision Matrix/Vector types?
This library looks very interesting, however, in our apps we also use a lot of single precision matrices and vectors shave off some memory usage. Would it be possible to add a single precision matrix and vector types?

### PR DESCRIPTION
**Pull request by atlemann**
Fixes: #19

### CODE REVIEW

**Comment by atlemann** [comment]
I basically copy pasted the original matrix and vector code and put it under the MKLNET.Single namespace. I'm not sure if that's the best way to do it, or if you'd want to use the same namespace and call the types matrix32 or matrixf or something instead?

**Comment by atlemann** [comment]
What would you like to do for tests? Copy the original ones under a `.Single` namespace and replace double with float?

**Comment by AnthonyLloyd** [comment]
Yes I think so. There may be an issue when you have a using for MKLNET & MKLNET.Single. Can you see how that goes. I'll test it out when you'd added some tests. Thanks

**Comment by atlemann** [comment]
I copied the vector and matrix tests. Some of it became a bit ugly with casting to double and to single again unfortunately. I also added a small example of having both precision types in the same scope in the SingleMatrixTests.

Not sure how to actually run the tests. I'm not able to build the MKL.NET.Native project. I guess I'm missing something locally due to this error:

```
[ 33%] Building C object CMakeFiles/MKL.NET.Native.dir/vsl.c.o
/home/aru/.nix-profile/bin/cc -DMKL_NET_Native_EXPORTS -I/home/aru/src/MKL.NET/MKL.NET.Native/../packages/devel/intelmkl.devel.linux-x64/lib/native/include -fPIC -Wall -Wextra -pedantic -Werror -MD -MT CMakeFiles/MKL.NET.Native.dir/vsl.c.o -MF CMakeFiles/MKL.NET.Native.dir/vsl.c.o.d -o CMakeFiles/MKL.NET.Native.dir/vsl.c.o -c /home/aru/src/MKL.NET/MKL.NET.Native/vsl.c
/home/aru/src/MKL.NET/MKL.NET.Native/vsl.c:2:10: fatal error: mkl_vsl.h: No such file or directory
    2 | #include "mkl_vsl.h"
      |          ^~~~~~~~~~~
compilation terminated.
```

**Comment by atlemann** [comment]
If you have no use for these changes, I fully understand if you don't want to pull this into the library due to the added maintenance burden.

**Comment by AnthonyLloyd** [comment]
You can compile the native library and run the tests by following what actions [CI](https://github.com/MKL-NET/MKL.NET/blob/master/.github/workflows/ci.yml#L21) does. 

The tests all work apart from some Atanpi etc which I've removed. Seems a simple enough extension of the functionality.

Released as MKT.NET.Matrix 1.1.0.

**Pull request merged**
